name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        workspace: flix.xcworkspace
        scheme: flix
        destination: platform=platform=iOS Simulator,name=iPhone 11 Pro
        action: test
